### ISSUE TITLE
-o ignored

### ISSUE THREAD

**Issue by carrere** [kentnf/iTAK#2]
Dear iTAK developpers,

The argument -o seems not to be taken into account to specify the output directory (release 1.7.a).

I fixed this bug just byt adding the line `$output_dir =  $$options{'o'} if (defined $$options{'o'}); ` at lines 68 and 165.

Sincerely,

Sebastien

**Comment by kentnf** [comment]
Than you for letting me know this bug. It has been fixed as your suggestion. 
Best,
Yi
