### ISSUE TITLE
ask for help, when run the itak on linux the error show "ValueError: could not convert string to float:"

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [kentnf/iTAK#6]
dear friend:
I  run the command with "python  ~/iTAK-2.0.2/iTAK.py  -p 3 -o hap1.itak -c hap1.pep1" , but its error with show "ValueError: could not convert string to float:"
![image](https://github.com/kentnf/iTAK/assets/101324838/5ee90a8b-8abc-4cd6-88a2-c31ced29e119)
its very weird, when I run the test fasta in your software, its ok ,and have the result, so I think maybe the software need the special format, so I use the seqkit seq to generate the new file, but its also error. so maybe the id was error , the original was like "Cannabis1G00001.t1", modified "Cannabis1G00001t1", its still error. other ways to try, I extract the 100 sequences to run, its down. but when extract the 200 sequences, still error .
so how handle with this question.
thank you

**Comment by kentnf** [comment]
Please send me the 100 - 200 sequence or the files in the "_temp" folder (kentnf@gmail.com) to reproduce the error. This error should be caused by incorrect processing of hmmscan output files.

**Comment by kentnf** [comment]
the bug has been fixed, please using git clone command to get the latest version.

**Comment by BioOmics** [comment]
After use  iTAK-2.0.2, still error.

![image](https://github.com/user-attachments/assets/53a36adb-b2b3-46d0-a012-fe09ebe37ce3)



My pep data: [test.zip](https://github.com/user-attachments/files/17794151/test.zip)
